services:
  backend:
    build:
      context: .
      dockerfile: ./dockerfiles/backend.Dockerfile
    ports:
      - 443:443
    environment:
      - MEETING_SUM_LISTEN_ADDR=0.0.0.0:50051

  frontend:
    build:
      context: .
      dockerfile: ./dockerfiles/frontend.Dockerfile
    ports:
      - 8080:3000
    depends_on:
      - backend
    environment:
      - MEETING_SUM_HEARTBEAT_INTERVAL=2000
      - MEETING_SUM_TRANSCRIBER_URL=backend:50051
      - MEETING_SUM_PROTO_DIR=./proto
